default_install_hook_types = ["pre-commit", "commit-msg"]
default_stages = ["pre-commit"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "check-merge-conflict" },
  { id = "check-added-large-files" },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.12.21"
hooks = [{ id = "uv-lock" }]

[[repos]]
repo = "https://github.com/compilerla/conventional-pre-commit"
rev = "v4.4.0"
hooks = [
  { id = "conventional-pre-commit", stages = ["commit-msg"], args = ["--strict"] },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-check"
name = "ruff check"
entry = "uv run ruff check --force-exclude"
language = "system"
types_or = ["python", "pyi"]
require_serial = true

[[repos.hooks]]
id = "ruff-format"
name = "ruff format"
entry = "uv run ruff format --force-exclude --check"
language = "system"
types_or = ["python", "pyi"]
require_serial = true

[[repos.hooks]]
id = "pyrefly-check"
name = "pyrefly check"
entry = "uv run pyrefly check"
language = "system"
types_or = ["python", "pyi"]
pass_filenames = false
require_serial = true

[[repos.hooks]]
id = "zizmor"
name = "zizmor"
entry = "uv run zizmor --no-progress"
language = "system"
files = '^\.github/workflows/[^/]+\.ya?ml$'
require_serial = true
